# Generated by Django 2.2 on 2019-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='icon',
            field=models.CharField(default='icon', max_length=200),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text',
            field=models.TextField(blank=True, default='text'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
